exports.domains = [
	'redstar.com'
	'rsmedia.com'
	'vinely.com'
	'gosprout.com'
	'loopit.com'
	'nevershopalone.com'
	'weunitetobuy.com'
]
exports.names = [
	'Aaron Kolenda'
	'Andrew Lau'
	'Annalisa Oswald'
	'Annie Chen'
	'Aatish Salvi'
	'Ben Donohue'
	'Bill Wittenberg'
	'Robert Kittler'
	'Bob Mason'
	'Christopher Howard'
	'David Joy'
	'David Rabinowitz'
	'Elizabeth Goede'
	'Elmer Moore'
	'Gina Maggio'
	'Inge Milde'
	'Jeet Singh'
	'Joel Marquis'
	'Jayme Mendal'
	'Jessica Merrell'
	'Joe Chung'
	'Krzysztof Baranowski'
	'Kate Hitchner'
	'Kwan Lee'
	'Luisa Groher'
	'Lucy Chung'
	'Marcus Wilhelm'
	'Mark Goodman'
	'Marshall Moutenot'
	'Matt Beecher'
	'miles grimshaw'
	'Maura Robinson'
	'Sam Sudore'
	'Soham Patel'
	'Scott Strawn'
	'Tyler Infelise'
]
exports.emails = [
]
